### PR TITLE
fix reference error

### LINKED ISSUE #994: [bincrafters-remove-outdated] Master broke due to new Conan versions
https://travis-ci.com/bincrafters/bincrafters-remove-outdated/builds/131071062

### PR DESCRIPTION
**Pull request by ericLemanissier**
ERROR: Value provided for package name, '...' (type ConanFileReference), is not a string

Fixes https://github.com/bincrafters/community/issues/994

### CODE REVIEW

**Comment by Croydon** [comment]
~~Does this fix https://github.com/bincrafters/community/issues/994 ? 🤔~~

~~I don't know the details anymore, but on a quick look it does not seem connected, so it is confusing to see CI go green~~

GitHub did not show me the full diff previously for some reason.

This fixes https://github.com/bincrafters/community/issues/994

**Comment by ericLemanissier** [comment]
yes, the fix for these tests is: https://github.com/bincrafters/bincrafters-remove-outdated/pull/6/files#diff-bf90e4a1121c77f4c3c9c965d06688dc

**Comment by Croydon** [comment]
You reply faster than I can edit my message :D 

Good job @ericLemanissier! Thanks for fixing it

**Review by Croydon — APPROVED** [review]

**Review by uilianries — APPROVED** [review]

**Comment by uilianries** [comment]
0.5.0 available now! https://pypi.org/project/bincrafters-remove-outdated/0.5.0/

**Comment by uilianries** [comment]
Thank you people for checking it! Cheers!

**Pull request merged**
